#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sun Sep 25 13:43:28 2016

import wx

# begin wxGlade: extracode
# end wxGlade



class MainStatusWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainStatusWindow.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "Online")
        self.list_online = wx.ListBox(self, -1, choices=[])
        self.label_2 = wx.StaticText(self, -1, "Offline")
        self.list_offline = wx.ListBox(self, -1, choices=[])
        self.label_3 = wx.StaticText(self, -1, "Log")
        self.list_log = wx.ListBox(self, -1, choices=[])
        self.button_options = wx.Button(self, -1, "&Options")
        self.button_quit = wx.Button(self, -1, "&Quit")
        self.label_status = wx.StaticText(self, -1, "Status")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX_DCLICK, self._on_list_online_dclick, self.list_online)
        self.Bind(wx.EVT_LISTBOX_DCLICK, self._on_list_offline_dclick, self.list_offline)
        self.Bind(wx.EVT_BUTTON, self._on_options_button_click, self.button_options)
        self.Bind(wx.EVT_BUTTON, self._on_button_quit, self.button_quit)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainStatusWindow.__set_properties
        self.SetTitle("twitch-notifier")
        self.SetSize((393, 527))
        self.button_options.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainStatusWindow.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.label_1, 0, wx.EXPAND, 0)
        sizer_1.Add(self.list_online, 0, wx.EXPAND, 0)
        sizer_1.Add(self.label_2, 0, wx.EXPAND, 0)
        sizer_1.Add(self.list_offline, 1, wx.EXPAND, 0)
        sizer_1.Add(self.label_3, 0, wx.EXPAND, 0)
        sizer_1.Add(self.list_log, 0, wx.EXPAND, 0)
        sizer_2.Add(self.button_options, 0, 0, 0)
        sizer_2.Add((20, 20), 1, wx.EXPAND, 0)
        sizer_2.Add(self.button_quit, 0, 0, 0)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        sizer_1.Add(self.label_status, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def _on_button_quit(self, event): # wxGlade: MainStatusWindow.<event_handler>
        print "Event handler `_on_button_quit' not implemented"
        event.Skip()

    def _on_list_online_dclick(self, event): # wxGlade: MainStatusWindow.<event_handler>
        print "Event handler `_on_list_online_dclick' not implemented"
        event.Skip()

    def _on_list_offline_dclick(self, event): # wxGlade: MainStatusWindow.<event_handler>
        print "Event handler `_on_list_offline_dclick' not implemented"
        event.Skip()

    def _on_options_button_click(self, event): # wxGlade: MainStatusWindow.<event_handler>
        print "Event handler `_on_options_button_click' not implemented"
        event.Skip()

# end of class MainStatusWindow


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MainStatusWindow(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
